# Generated by Django 2.2 on 2021-02-18 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='title',
            field=models.CharField(default='hello', max_length=100),
            preserve_default=False,
        ),
    ]
